// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Mon Apr 29 18:09:15 2019

ledMatrix ledMatrix_inst
(
	.MCLK(MCLK_sig) ,	// input  MCLK_sig
	.source_valid(source_valid_sig) ,	// input  source_valid_sig
	.F_BIN_IN(F_BIN_IN_sig) ,	// input [BIN_WDITH-1:0] F_BIN_IN_sig
	.RESET(RESET_sig) ,	// input  RESET_sig
	.RGB1(RGB1_sig) ,	// output [2:0] RGB1_sig
	.RGB2(RGB2_sig) ,	// output [2:0] RGB2_sig
	.ROW_ADDRESS(ROW_ADDRESS_sig) ,	// output [3:0] ROW_ADDRESS_sig
	.CLK_MATRIX(CLK_MATRIX_sig) ,	// output  CLK_MATRIX_sig
	.LATCH(LATCH_sig) ,	// output  LATCH_sig
	.OE(OE_sig) ,	// output  OE_sig
	.GND(GND_sig) 	// output [2:0] GND_sig
);

defparam ledMatrix_inst.BIN_WDITH = 24;
defparam ledMatrix_inst.BUFFER_WIDTH = 10;
//defparam ledMatrix_inst.BUFFER_SIZE_NO = ;
defparam ledMatrix_inst.SCREEN_WIDTH = 64;
defparam ledMatrix_inst.SCREEN_WIDTH_BITS = 6;
defparam ledMatrix_inst.SCREEN_LENGTH = 32;
defparam ledMatrix_inst.SCREEN_LENGTH_BITS = 5;
defparam ledMatrix_inst.OE_HOLD = 1000;
