// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Mon Apr 22 19:27:14 2019

ledMatrix ledMatrix_inst
(
	.MCLK(MCLK_sig) ,	// input  MCLK_sig
	.source_vaid(source_vaid_sig) ,	// input  source_vaid_sig
	.F_BIN_IN(F_BIN_IN_sig) ,	// input [BIN_WDITH-1:0] F_BIN_IN_sig
	.RESET(RESET_sig) ,	// input  RESET_sig
	.R1(R1_sig) ,	// output  R1_sig
	.G1(G1_sig) ,	// output  G1_sig
	.B1(B1_sig) ,	// output  B1_sig
	.R2(R2_sig) ,	// output  R2_sig
	.G2(G2_sig) ,	// output  G2_sig
	.B2(B2_sig) ,	// output  B2_sig
	.A(A_sig) ,	// output  A_sig
	.B(B_sig) ,	// output  B_sig
	.C(C_sig) ,	// output  C_sig
	.D(D_sig) ,	// output  D_sig
	.CLK_MATRIX(CLK_MATRIX_sig) ,	// output  CLK_MATRIX_sig
	.LATCH(LATCH_sig) ,	// output  LATCH_sig
	.OE(OE_sig) 	// output  OE_sig
);

defparam ledMatrix_inst.MTRX_HEIGHT = 32;
defparam ledMatrix_inst.MTRX_LENGTH = 64;
defparam ledMatrix_inst.BIN_WDITH = 24;
defparam ledMatrix_inst.BUFFER_WIDTH = 8;
